"""empty message

Revision ID: 450600fd7864
Revises: fcc3038adf2b
Create Date: 2019-06-28 20:31:04.485654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450600fd7864'
down_revision = 'fcc3038adf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'admin', ['username'], unique=True)
    # ### end Alembic commands ###
