"""empty message

Revision ID: 8fb0093a85a2
Revises: e8b92c20b9a5
Create Date: 2019-06-30 10:12:39.678964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fb0093a85a2'
down_revision = 'e8b92c20b9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_moel', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('art_moel', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('art_moel', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('art_moel', sa.Column('describe', sa.String(length=100), nullable=True))
    op.add_column('art_moel', sa.Column('keywords', sa.String(length=100), nullable=True))
    op.add_column('art_moel', sa.Column('tags', sa.String(length=100), nullable=True))
    op.add_column('art_moel', sa.Column('title', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'art_moel', ['title'])
    op.create_foreign_key(None, 'art_moel', 'category', ['category'], ['id'])
    op.drop_column('art_moel', 'codename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_moel', sa.Column('codename', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'art_moel', type_='foreignkey')
    op.drop_constraint(None, 'art_moel', type_='unique')
    op.drop_column('art_moel', 'title')
    op.drop_column('art_moel', 'tags')
    op.drop_column('art_moel', 'keywords')
    op.drop_column('art_moel', 'describe')
    op.drop_column('art_moel', 'date')
    op.drop_column('art_moel', 'content')
    op.drop_column('art_moel', 'category')
    # ### end Alembic commands ###
