"""empty message

Revision ID: e8b92c20b9a5
Revises: ef3c873b55f5
Create Date: 2019-06-29 20:15:11.583758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b92c20b9a5'
down_revision = 'ef3c873b55f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('key_word', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'key_word')
    # ### end Alembic commands ###
