"""empty message

Revision ID: ef3c873b55f5
Revises: fce217147365
Create Date: 2019-06-29 19:58:29.328441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3c873b55f5'
down_revision = 'fce217147365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catename', sa.String(length=100), nullable=True),
    sa.Column('as_name', sa.String(length=20), nullable=True),
    sa.Column('descri', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_name'),
    sa.UniqueConstraint('catename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
