"""empty message

Revision ID: fce217147365
Revises: 8fc775afb9df
Create Date: 2019-06-29 19:06:12.765863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fce217147365'
down_revision = '8fc775afb9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_moel', sa.Column('codename', sa.Text(), nullable=True))
    op.drop_index('name', table_name='art_moel')
    op.drop_column('art_moel', 'name')
    op.drop_column('art_moel', 'values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_moel', sa.Column('values', mysql.TEXT(), nullable=True))
    op.add_column('art_moel', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('name', 'art_moel', ['name'], unique=True)
    op.drop_column('art_moel', 'codename')
    # ### end Alembic commands ###
